### ISSUE TITLE
Pidgin crashes when somebody use "Start a Discussion" (e.g. from webapp)

### ISSUE THREAD

**Issue by Mi-La** [EionRobb/purple-rocketchat#16]
Using latest master, the plugin causes whole Pidgin crash since somebody use "Start a Discussion". Please see the attached backtrace.

```
Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
__strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
```
[pidgin-backtrace.log](https://github.com/EionRobb/purple-rocketchat/files/5775114/pidgin-backtrace.log)

When running the pidgin via gdb, it seems that a new window for the discussion is created with some random name - e.g. "RvwHoPGXuTbA3dxsj" .... but than the SIGSEGV appears.

**Comment by Mi-La** [comment]
I think I've the problem. In `librocketchat.c:1380`, there is a call to `rc_markdown_to_html` and the `msg_text` argument is NULL. The `rc_markdown_to_html` uses `strlen` on that NULL argument here: `librocketchat.c:388`.

Note that `strlen` doesn't check for NULL and causes SEGFAULT. I did a quick hack to prevent crash by changing the line 388 from:
`markdown_len = mkd_line((char *)markdown, strlen(markdown), &markdown_str, flags);`
to:
`markdown_len = mkd_line((char *)markdown, markdown != NULL ? strlen(markdown) : 0, &markdown_str, flags);`

At least it doesn't crash anymore and the message display correctly in a new "room-like" window.

**Comment by Mi-La** [comment]
Should I create a pull request with the one-liner hot fix? :-).

**Comment by EionRobb** [comment]
Sorry, received your bug report while I was on holiday and put it on the backburner

Rather than doing stuff inline, would it be better to return `NULL` from `rc_markdown_to_html` if the input is also `NULL` so that it doesn't need to go through the libdiscount calls unnecessairly?

**Comment by Mi-La** [comment]
If you have time to do it properly, please just fix it. I don't need to have my own pull request merged ;-). I was happy enough to temporarily fix the crash and report the issue.
FYI: There are more problems with rooms, e.g. after pidgin restart, I don't get new messages from "rooms"/discussions (even though I have `auto join` and `persistent` options checked) . But sometimes the messages suddenly arrive, I think that it happens when some user who is in the room changes his status.

**Comment by EionRobb** [comment]
Fair enough, wasn't about who gets credit for what, but you're more able to recreate the issue so more able to confirm a fix :)

Can you try with the above commit and see if that helps?

**Comment by Mi-La** [comment]
Fix verified, works well. Thanks.

I'll try to investigate the FYI part of my last comment when I have more time.

**Comment by EionRobb** [comment]
Awesome, thanks for confirming :)

Appreciate the issue reports :)
