### ISSUE TITLE
Can't connect to server ("Lost connection to server")

### ISSUE THREAD

**Issue by iv4nhoe** [EionRobb/purple-rocketchat#24]
When trying to connect to Rocket.Chat I get "Lost connection to server" in the status area and in the debug window there's a lot of messages saying "unknown websocket error" (see [connect.log](https://github.com/EionRobb/purple-rocketchat/files/8284045/connect.log)).
The server is running version 4.0.5.

**Comment by EionRobb** [comment]
It looks like there's a bit of info cut off from before the "Fetching url..." line.  Can you get another debug log, started from just before hitting the 'reconnect'?

**Comment by iv4nhoe** [comment]
Oh sorry, I just grepped for "rocketchat". Ok, here is a complete log from the reconnection phase:
[pidgin.log](https://github.com/EionRobb/purple-rocketchat/files/8302754/pidgin.log)

**Comment by iv4nhoe** [comment]
For future reference, this was an issue with the Rocket.Chat server. @EionRobb noticed that there's a 500 server error when connecting to the websocket on that server. I contacted the server admin and they fixed it. Apparently `proxy_wstunnel` was missing from their server configuration.
