### ISSUE TITLE
Plugin stopped working after the last rocketchat update

### ISSUE THREAD

**Issue by KrisBuytaert** [EionRobb/purple-rocketchat#25]
After a recent rocketchat upgrade to 4.6.1  the plugin stopped working 

(09:27:03) rocketchat: Got response: {"info":{"version":"4.6.1","build":{"date":"2022-04-07T16:34:14.412Z","nodeVersion":"v14.18.3","arch":"x64","platform":"linux","osRelease":"5.13.0-1021-azure","totalMemory":7283847168,"freeMemory":1151143936,"cpus":2},"commit":{"hash":"174728c96ead31f3e81bf405e72c32b32a622bd3","date":"Thu Apr 7 13:09:47 2022 -0300","author":"Diego Sampaio","subject":"Merge pull request #25095 from RocketChat/release-4.6.1","tag":"4.6.1","branch":"HEAD"},"marketplaceApiVersion":"1.31.0"},"success":true}
(09:27:03) rocketchat: got frame data: o

On the server side logs I don't see any errors 
Above is a snippet from the client debug log  ... not sure how to debug this further ..

**Comment by EionRobb** [comment]
Is that the full debug log from pidgin? Are you using the latest code in master?

**Comment by KrisBuytaert** [comment]
@EionRobb  thanks for waking me up .. I assumed I was indeed using the last version of the code, turned out I wasn't  sorry for bothering you ..  it's working again

**Comment by EionRobb** [comment]
No worries, glad you got it working again :) 

Might have been after the breakage in 4.4, see https://github.com/EionRobb/purple-rocketchat/issues/23
